public class foo {
	
	public String myProperty { get; set; }

	public foo(Integer i) {
		Fuck<shit> poop = 'crap';
		String bat = 'bar';
		Foo j = 0;
	}

	public PageReference fuck() {
		List<Id> foo = null;
		Set<String> bar = new Set<String>();
		return null;
	}

	void foobar() {
		String foo = 'bar';
		String bar = 'bat';
		Contact c = [Select id from foo];
		for (Integer i=0; i<10; i++) {
			update c;
			Account a = [select id from account];
		}
	}

	public List<String> getSomeString() {
		return 'foo';
		//List<Account> foos = [SELECT ID FROM ACCOUNT];
		Account a = [Select ID FROM Account];
		Account a = [Select ID FROM Account];
	}

	public Set<Id> getSomething() {
		return null;
	} 

	public Set<String> getSomeStringFOO() {
		return 'foo';
		//List<Account> foos = [SELECT ID FROM ACCOUNT];
		Account a = [Select ID FROM Account];
		Account a = [Select ID FROM Account];
	}
}